### ISSUE TITLE
Documentation about daemon mode

### ISSUE THREAD

**Issue by Nightbr** [wachterjohannes/sulu-docker#3]
Hey,

I think it could be nice to have documentation on how to run the stack as daemon:

https://github.com/EugenMayer/docker-sync/wiki/2.3-daemon-mode

START
```
#docker-sync-daemon start # not needed anymore
docker-sync start
docker-compose up -d
```

STOP
```
docker-compose stop
docker-sync stop
```

REMOVE
```
docker-compose down
docker-sync stop
```

**Comment by niklasnatter** [comment]
The `Startup Containers` section contains an example how to start the containers in background now. Thanks for reporting this!
