### ISSUE TITLE
Update README for new structure

### ISSUE THREAD

**Issue by Khartir** [wachterjohannes/sulu-docker#46]
The Initialize Sulu part of the readme does not work with the current dev-branch (and I assume Version 2 of Sulu). Since the readme specifies to use the dev-branch during install, this should be changed.

**Comment by niklasnatter** [comment]
Hey,
thanks for raising this issue. I guess you are talking about the `app/config/parameters.yml` part?

I just created a small PR to adjust that section: #47 
Could you test the new instructions and confirm if they are working for you?
