### ISSUE TITLE
 X-Pack plugin license problems

### ISSUE THREAD

**Issue by kfrohwein** [wachterjohannes/sulu-docker#50]
The Login to Kibana fails because of this message:

> Login is currently disabled because the license could not be determined. Please check that
> Elasticsearch has the X-Pack plugin installed and is reachable, then refresh this page.

I googled a bit for it and it seems https://github.com/elastic/kibana-docker is abandoned and the docker images by Elastic Inc. should be used now.

**Comment by alexander-schranz** [comment]
@kfrohwein thank you for the issue we did discuss it internal and we will remove kibana from the sulu-docker to keep the things simple. And serve elasticsearch as an optional service.

**Comment by niklasnatter** [comment]
Thanks for reporting! I think this is not relevant anymore after we restructured the project in https://github.com/sulu/sulu-docker/pull/51
